name: Shopify Lighthouse CI
on:
    workflow_dispatch:
    workflow_call:        
jobs:
  lhci:
    name: Lighthouse
    environment: LHCI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lighthouse
      uses: shopify/lighthouse-ci-action@v1
      with:
        access_token: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        store: ${{ secrets.SHOPIFY_STORE }}
        password: ${{ secrets.SHOPIFY_STORE_PASSWORD }}
        pull_theme: LHCI
        lhci_github_app_token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        lhci_min_score_performance: 0.9
