name: shopify-sync
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-dev-branch:
    runs-on: ubuntu-latest
    steps:
      - name: user
        shell: bash
        if: ${{ github.actor }} == "shopify[bot]"
        run: echo "mergedev=$(echo 1)" >> $GITHUB_ENV
      - name: branch
        shell: bash
        if: startsWith(${{ github.ref }}, 'refs/heads/hotfix')
        run: echo "mergedev=$(echo 1)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync develop branch
        if: ${{ vars.mergedev }} == 1
        shell: bash
        run: ./.scripts/syncdev.sh
