name: shopify-sync
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-dev-branch:
    runs-on: ubuntu-latest
    steps:
      - name: user
        shell: bash
        run: echo ${{ github.actor }}
      - name: branch
        shell: bash
        run: echo startsWith(${{ github.ref }}, 'refs/heads/hotfix')
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync develop branch
        if: false
        shell: bash
        run: ./.scripts/syncdev.sh