name: shopify-sync
run-name: sync dev branch and deploy to QA
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  testOutput:
    runs-on: ubuntu-latest
    outputs:
      mergedev: ${{ steps.setouput.output.mergedev }}
    steps:
      - name: set-output
        id: setouput
        shell: bash
        run: echo "mergedev=1">>$GITHUB_OUTPUT
      - name: test output
        run: echo ${{ steps.setouput.outputs.mergedev }}
      
  test:
    runs-on: ubuntu-latest
    needs: testOutput
    steps:
      - name: test output
        run: echo ${{ needs.testOutput.outputs.mergedev }}
      - uses: henrygriffiths/debug_action@v1
        with:
          contexts: 'needs'         
          needs_context: ${{ toJson(needs) }}

#  deploy:
#    uses: ./.github/workflows/deploy.yml
#    needs: sync-dev-branch
#    if: needs.sync-dev-branch.outputs.output == 1
#    with:
#      environment: QA
#      branch: develop