name: shopify-sync
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-dev-branch:
    runs-on: ubuntu-latest
    steps:
      - name: user
        if: false
        shell: bash
        run: |
          echo ${{github.actor}}
          echo "mergedev=$(echo 1)">>$GITHUB_ENV
      - name: branch
        if: startsWith(${{github.ref}}, 'refs/heads/hotfix')
        shell: bash
        run: echo "mergedev=$(echo 1)">>$GITHUB_ENV
      - name: check
        shell: bash
        run: echo ${{ vars.mergedev }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync develop branch
        if: ${{ vars.mergedev }} == 1
        shell: bash
        run: ./.scripts/syncdev.sh
