name: shopify-deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: QA
      branch: develop