name: shopify-deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["shopify-sync"]
    types: [completed]
    branches:
      - 'main'
jobs:
  deploy:
    name: Deploy
    environment: QA
    runs-on: ubuntu-latest
    steps:
      - name: Validate is hook from sync
        if: github.event_name == 'workflow_run'
        shell: bash
        run: echo branch=develop >> $GITHUB_ENV
      - name: Set branch
        if: vars.branch != 'develop'
        shell: bash
        run: echo branch=${{github.ref_name}}
      - name: Check branch
        shell: bash
        run: echo ${{vars.branch}}

