name: shopify-sync
run-name: sync dev branch and deploy to QA
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-dev-branch:
    runs-on: ubuntu-latest
    outputs:
      mergedev: ${{ steps.setOuputStep.output.test }}
    steps:
      - name: user
        if: github.actor == 'shopify[bot]'
        shell: bash
        run: echo "mergedev=1">>$GITHUB_ENV
      - name: branch
        if: startsWith(github.ref, 'refs/heads/hotfix')
        shell: bash
        run: echo "mergedev=1">>$GITHUB_ENV
      - name: set output
        id: setOuputStep
        shell: bash
        run: echo "output=${{ env.mergedev }}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync develop branch
        if: env.mergedev == 1
        shell: bash
        run: ./.scripts/syncdev.sh
      - name: Sync develop branch
        shell: bash
        run: ls -la ./.scripts
      - uses: ./.github/workflows/deploy.yml
        

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: sync-dev-branch
    if: needs.sync-dev-branch.outputs.output == 1
    with:
      environment: QA
      branch: develop