name: shopify-deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
  pull-request:
    branches:
      - 'develop'
    types:
      [closed]
jobs:
  deploy:
    name: Deploy
    environment: QA
    runs-on: ubuntu-latest
    steps:
      - name: Validate is hook from sync
        if: github.event_name == 'workflow_run'
        shell: bash
        run: |
          echo "branch=develop" >> $GITHUB_ENV
          echo "deploy=1" >> $GITHUB_ENV
      - name: Set branch
        if: env.branch != 'develop'
        shell: bash
        run: |
          echo "branch=${{github.ref_name}}" >> $GITHUB_ENV
          echo "deploy=1" >> $GITHUB_ENV
      - name: Check branch
        shell: bash
        run: echo ${{env.branch}}
      - name: Check pull request merged
        shell: bash
        run: |
          echo "${{github.event.pull_request}}"
      - uses: actions/checkout@v1
        with:
          ref: ${{ env.branch }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
      - name: Deploy
        env:
          SHOPIFY_FLAG_STORE: '${{ secrets.SHOPIFY_STORE }}'
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_CLI_TTY: 0
        run: shopify theme push --path . --theme ${{ vars.SHOPIFY_THEME_ID }}
