name: shopify-sync
run-name: Sync branches
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-dev-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: bash ./.scripts/syncdev.sh