name: test-dev-deploy
on:
  workflow_dispatch:
jobs:
  dev-deploy:
    name: temporal deploy
    runs-on: ubuntu-latest
    environment: LHCI
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: "latest"
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
      - name: Deploy
        env:
          SHOPIFY_FLAG_STORE: "${{ secrets.SHOPIFY_STORE }}"
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_CLI_TTY: 0
        run: |
          shopify theme push --path . --development
